[project]
authors = ["≈Åukasz Kalbarczyk"]
entry = "prices.sw"
forc-version = "0.36.0"
license = "Apache-2.0"
name = "prices"
organization = "RedStone"

[dependencies]
redstone = { path = "../redstone" }
