name: Long primary dry run test
on:
  push:
    branches: ["main"]
  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  long-primary-dry-run:
    runs-on: self-hosted
    timeout-minutes: 15
    steps:
      - uses: actions/checkout@v3
      - name: Install deps
        run: yarn --frozen-lockfile --immutable
      - name: Build all
        run: |
          echo 0 > STATUS_TMP
          cd packages/cache-service && yarn build || echo 1 > STATUS_TMP  &
          cd packages/evm-connector && yarn compile && yarn build || echo 2 > STATUS_TMP  &
          cd packages/oracle-node && yarn build || echo 3 > STATUS_TMP  &
          cd packages/on-chain-relayer && yarn compile && yarn build || echo 4 > STATUS_TMP  &

          wait
          exit $(cat STATUS_TMP)
      - name: Run long primary dry run tests
        run: yarn ts-node src/primary-long-price-propagation-core.ts
        working-directory: packages/integration
        env:
          NODE_ENV: test
          COINGECKO_API_URL: https://pro-api.coingecko.com/api/v3/simple/price
          COINGECKO_API_KEY: ${{ secrets.COINGECKO_API_KEY }}
          COINMARKETCAP_API_KEY: ${{ secrets.COINMARKETCAP_API_KEY }}
          KAIKO_API_KEY: ${{ secrets.KAIKO_API_KEY }}
          TWELVE_DATA_API_KEY: ${{ secrets.TWELVE_DATA_API_KEY }}
          STLOUISFED_API_KEY: ${{ secrets.STLOUISFED_API_KEY }}
          SKIPPED_SOURCES: '["bybit"]'
