name: Monorepo integration tests

on:
  push:
    branches: "**"

jobs:
  core:
    runs-on: LargeRunner
    defaults:
      run:
        working-directory: packages/integration
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 18.15
      - name: Install deps
        run: yarn
      - name: Build
        run: yarn build
      - name: Lint
        run: yarn lint
      - name: Run core tests - simple propagation
        run: node dist/simple-price-propagation-core.js
        env:
          NODE_ENV: test
  core-with-node-failure:
    runs-on: LargeRunner
    defaults:
      run:
        working-directory: packages/integration
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 18.15
      - name: Install deps
        run: yarn
      - name: Build
        run: yarn build
      - name: Run tests - node failures
        run: node dist/prices-updates-node-failures.js
        env:
          NODE_ENV: test
  classic:
    runs-on: LargeRunner
    defaults:
      run:
        working-directory: packages/integration
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 18.15
      - name: Install deps
        run: yarn
      - name: Build
        run: yarn build
      - name: Run classic tests - simple propagation
        run: node dist/simple-price-propagation-classic.js
        env:
          NODE_ENV: test
