name: Integration tests

on:
  push:
    branches: ["**"]

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  integration-tests-core:
    uses: ./.github/workflows/integration-test-template.yml
    with:
      command: yarn ts-node src/simple-price-propagation-core.ts
  integration-tests-core-with-node-failure:
    uses: ./.github/workflows/integration-test-template.yml
    with:
      command: yarn ts-node src/prices-updates-node-failures.ts
  integration-tests-classic:
    uses: ./.github/workflows/integration-test-template.yml
    with:
      command: yarn ts-node src/simple-price-propagation-classic.ts
  integration-test-classic-relayer-condition-cron:
    uses: ./.github/workflows/integration-test-template.yml
    with:
      command: yarn ts-node src/relayer-conditions/relayer-cron-condition.ts
  integration-test-classic-relayer-condition-time:
    uses: ./.github/workflows/integration-test-template.yml
    with:
      command: yarn ts-node src/relayer-conditions/relayer-time-condition.ts
  integration-test-classic-relayer-condition-value-deviation:
    uses: ./.github/workflows/integration-test-template.yml
    with:
      command: yarn ts-node src/relayer-conditions/relayer-value-deviation-condition.ts
  integration-test-classic-relayer-condition-value-deviation-and-time:
    uses: ./.github/workflows/integration-test-template.yml
    with:
      command: yarn ts-node src/relayer-conditions/relayer-value-and-time-condition.ts
  integration-test-classic-relayer-one-node-down:
    uses: ./.github/workflows/integration-test-template.yml
    with:
      command: yarn ts-node src/relayer-conditions/relayer-one-rpc-down.ts
