name: On-chain relayer CI
on:
  push:
    paths:
      - packages/on-chain-relayer/**
      - .github/workflows/on-chain-relayer-tests.yml
      - .github/workflows/on-chain-relayer-deploy-to-ecr.yml

jobs:
  run-tests:
    runs-on: ubuntu-latest
    timeout-minutes: 10
    defaults:
      run:
        working-directory: packages/on-chain-relayer
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 18.15
      - name: Install modules
        run: yarn
      - name: Compile contracts
        run: yarn compile
      - name: Compile evm-connector
        run: cd ../evm-connector && yarn compile
      - name: Build
        run: yarn build
      - name: Run tests
        run: yarn test
        env:
          NODE_ENV: test
