name: On-chain relayer CI
on:
  push:
    paths:
      - packages/on-chain-relayer/**
      - .github/workflows/on-chain-relayer-tests.yaml
      - .github/workflows/on-chain-relayer-deploy-to-ecr-public.yaml

jobs:
  run-tests:
    runs-on: LargeRunner
    defaults:
      run:
        working-directory: packages/on-chain-relayer
    steps:
      - uses: actions/checkout@v3
      - name: Build dependent packages
        run: cd ../rpc-providers && yarn build
      - name: Install modules
        run: yarn
      - name: Compile contracts
        run: yarn compile
      - name: Build
        run: yarn build
      - name: Run tests
        run: yarn test
        env:
          NODE_ENV: test
