name: Oracle primary dry run test
on:
  push:
    paths:
      - packages/oracle-node/**
      - .github/workflows/oracle-primary-dry-run-test.yml

jobs:
  primary-dry-run-test:
    runs-on: ubuntu-latest
    timeout-minutes: 10
    defaults:
      run:
        working-directory: packages/oracle-node
    steps:
      - uses: actions/checkout@v3
      - name: Install modules
        run: yarn
      - name: Build
        run: yarn build
      - name: Run dry run test
        run: yarn test:primary-dry-run
        env:
          NODE_ENV: test
          COINGECKO_API_URL: https://pro-api.coingecko.com/api/v3/simple/price
          COINGECKO_API_KEY: ${{ secrets.COINGECKO_API_KEY }}
          KAIKO_API_KEY: ${{ secrets.KAIKO_API_KEY }}
          TWELVE_DATA_API_KEY: ${{ secrets.TWELVE_DATA_API_KEY }}
          STLOUISFED_API_KEY: ${{ secrets.STLOUISFED_API_KEY }}
          HISTORICAL_DATA_PACKAGES_URL: https://oracle-gateway-2.a.redstone.finance
          SKIPPED_SOURCES: '["binance", "binancecoinm", "binanceusdm", "bybit"]'
