name: Oracle Node CI
on:
  push:
    paths:
      - packages/oracle-node/**
      - .github/workflows/oracle-tests.yaml
      - .github/workflows/deploy-to-ecr-public.yaml

jobs:
  tests:
    runs-on: LargeRunner
    defaults:
      run:
        working-directory: packages/oracle-node
    steps:
      - uses: actions/checkout@v3
      - name: Install modules
        run: yarn
      - name: Build
        run: yarn build
      - name: Run tests
        run: yarn test:ci
        env:
          NODE_ENV: test
      - name: Run dry run test
        run: yarn test:dry-run
        env:
          NODE_ENV: test
          STLOUISFED_API_KEY: ${{ secrets.STLOUISFED_API_KEY }}
